version: '3.7'
services:
  frontend:
    image: bomis1/flaskapp:latest
    deploy:
      replicas: 1
    ports:
    - published: 5000
      target: 5000
    depends_on:
      - backend
  backend:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toimeme
      MYSQL_DATABASE: flaskmysq3
volumes:
  mysql-data: